# Generated by Django 4.2.23 on 2025-06-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TipoClientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipos', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='contactManagement_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('date_begin', models.DateField(unique=True)),
                ('date_end', models.DateField(unique=True)),
                ('description', models.TextField(null=True)),
                ('contract_value', models.FloatField(blank=True, max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaodecontratos.clientes')),
                ('type_client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaodecontratos.tipoclientes')),
            ],
        ),
    ]
