# Generated by Django 4.2.23 on 2025-06-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TipoClientes',
            new_name='TipoContratos',
        ),
        migrations.RemoveField(
            model_name='contactmanagement_db',
            name='type_client',
        ),
        migrations.AddField(
            model_name='contactmanagement_db',
            name='type_contract',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='gestaodecontratos.tipocontratos', verbose_name='Contract Type'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contactmanagement_db',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaodecontratos.clientes', verbose_name='Client'),
        ),
        migrations.AlterField(
            model_name='contactmanagement_db',
            name='contract_value',
            field=models.FloatField(blank=True, max_length=100, verbose_name='Contract Value'),
        ),
        migrations.AlterField(
            model_name='contactmanagement_db',
            name='date_begin',
            field=models.DateField(unique=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='contactmanagement_db',
            name='date_end',
            field=models.DateField(unique=True, verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='contactmanagement_db',
            name='description',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='contactmanagement_db',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('rascunho', 'rascunho'), ('encerrado', 'Encerrado')], max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='contactmanagement_db',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Contract Title'),
        ),
    ]
