# Generated by Django 4.2.23 on 2025-06-30 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0002_rename_tipoclientes_tipocontratos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmanagement_db',
            name='type_contract',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gestaodecontratos.tipocontratos', verbose_name='Contract Type'),
        ),
    ]
