# Generated by Django 4.2.23 on 2025-06-30 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0003_alter_contactmanagement_db_type_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmanagement_db',
            name='status',
            field=models.CharField(choices=[('ativo', 'Ativo'), ('rascunho', 'Rascunho'), ('encerrado', 'Encerrado')], max_length=100, verbose_name='Status'),
        ),
    ]
