# Generated by Django 4.2.23 on 2025-06-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0005_alter_contactmanagement_db_date_begin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmanagement_db',
            name='date_begin',
            field=models.CharField(max_length=8, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='contactmanagement_db',
            name='date_end',
            field=models.CharField(max_length=8, verbose_name='End Date'),
        ),
    ]
