# Generated by Django 4.2.23 on 2025-07-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0007_alter_contactmanagement_db_date_begin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmanagement_db',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='visualizacaocontrato/', verbose_name='Document'),
        ),
    ]
