# Generated by Django 4.2.23 on 2025-07-03 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0008_contactmanagement_db_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmanagement_db',
            name='contract_id',
            field=models.CharField(blank=True, editable=False, max_length=10, null=True, unique=True, verbose_name='Contract ID'),
        ),
    ]
