# Generated by Django 4.2.23 on 2025-07-03 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0009_contactmanagement_db_contract_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('type', models.CharField(choices=[('pessoa_fisica', 'Pessoa Física'), ('pessoa_juridica', 'Pessoa Jurídica')], max_length=100, verbose_name='Tipo de Cliente')),
                ('cnpjoucpf', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ/CPF do Cliente')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email do Cliente')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telefone do Cliente')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Endereço do Cliente')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade do Cliente')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado do Cliente')),
                ('zip_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='CEP do Cliente')),
            ],
        ),
        migrations.AlterField(
            model_name='tipocontratos',
            name='tipos',
            field=models.CharField(choices=[('manutencao', 'Manutenção'), ('servicos', 'Serviços'), ('suprimentos', 'Suprimentos'), ('Internet', 'Internet'), ('telefonia', 'Telefonia')], max_length=100),
        ),
    ]
