# Generated by Django 4.2.23 on 2025-07-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0010_client_alter_tipocontratos_tipos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_name', models.CharField(max_length=255, verbose_name='Nome do Lembrete')),
                ('reminder_type', models.CharField(max_length=100, verbose_name='Tipo')),
                ('reminder_date', models.DateField(verbose_name='Data do Lembrete')),
                ('notify_days_before', models.IntegerField(verbose_name='Dias antes para notificar')),
                ('frequency', models.CharField(choices=[('once', 'Única'), ('daily', 'Diária'), ('weekly', 'Semanal'), ('monthly', 'Mensal')], max_length=20, verbose_name='Frequência')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestaodecontratos.contactmanagement_db')),
            ],
        ),
    ]
