# Generated by Django 4.2.23 on 2025-07-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0011_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='notify_days_before',
            field=models.CharField(max_length=2, verbose_name='Dias antes para notificar'),
        ),
    ]
