# Generated by Django 4.2.23 on 2025-07-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0012_alter_reminder_notify_days_before'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='reminder_type',
            field=models.CharField(blank=True, choices=[('manutencao', 'Manutenção'), ('servicos', 'Serviços'), ('suprimentos', 'Suprimentos'), ('Internet', 'Internet'), ('telefonia', 'Telefonia')], max_length=100, null=True, verbose_name='Tipo'),
        ),
    ]
