# Generated by Django 4.2.23 on 2025-07-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0013_alter_reminder_reminder_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='visualizado',
            field=models.BooleanField(default=False),
        ),
    ]
