# Generated by Django 4.2.23 on 2025-07-09 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0015_alter_contactmanagement_db_type_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='Telefone do Cliente'),
        ),
        migrations.AlterField(
            model_name='client',
            name='zip_code',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='CEP do Cliente'),
        ),
    ]
