# Generated by Django 4.2.23 on 2025-07-09 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0016_alter_client_phone_alter_client_zip_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email Usuario')),
                ('password', models.CharField(blank=True, max_length=100, null=True, verbose_name='Senha')),
            ],
        ),
    ]
