# Generated by Django 4.2.23 on 2025-07-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0017_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='email_register',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='register',
            name='password_again',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Repetição Senha'),
        ),
    ]
