# Generated by Django 4.2.23 on 2025-07-09 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0018_register_email_register_register_password_again'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email Usuario'),
        ),
    ]
