# Generated by Django 4.2.23 on 2025-07-09 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0019_alter_register_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nome de Usuário'),
        ),
    ]
