# Generated by Django 4.2.23 on 2025-07-10 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0020_alter_register_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Register',
            new_name='User',
        ),
    ]
