# Generated by Django 4.2.23 on 2025-07-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0021_rename_register_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
