# Generated by Django 4.2.23 on 2025-07-14 19:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0022_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('arquivo', models.FileField(upload_to='documentos/')),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='gestaodecontratos.contactmanagement_db')),
            ],
        ),
    ]
