# Generated by Django 4.2.23 on 2025-07-16 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0024_alter_contactmanagement_db_type_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmanagement_db',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gestaodecontratos.client', verbose_name='Client'),
        ),
        migrations.DeleteModel(
            name='Clientes',
        ),
    ]
