# Generated by Django 4.2.23 on 2025-07-16 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaodecontratos', '0025_alter_contactmanagement_db_client_delete_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmanagement_db',
            name='client',
        ),
        migrations.AddField(
            model_name='contactmanagement_db',
            name='client',
            field=models.ManyToManyField(to='gestaodecontratos.client', verbose_name='Client'),
        ),
    ]
